dapecon/dapecon/dapapp/urls.py
from django.urls import path
from . import views
from .views import post_detail

app_name = 'dap'

urlpatterns = [
    path('thankyou', views.thank_you, name='thankyou_page'),
    path('contact/', views.contact_view, name='contact_view1'),
    path('', views.arxiki, name='arxiki'),
    path('istoria/', views.istoria, name='istoria'),
    path('anakinoseis/', views.blogs, name='anakinoseis'),
    path('post/<slug:slug>/', post_detail, name='post_detail'),
    path('anakinosi/<slug:slug1>/', views.post_detail1, name='post_detail1'),
    path('ideas/<slug:slug2>/', views.post_detail2, name='post_detail2'),



    ]

dapecon/dapecon/dapecon/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dapapp.urls')),
]

dapecon/dapecon/dapapp/models.py
from django.db import models
from django.core.validators import MinLengthValidator


class ContactMessage(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    phone = models.CharField(max_length=15)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)


class Tag(models.Model):
    caption = models.CharField(max_length=20)


class Author(models.Model):
    firstname = models.CharField(max_length=100)
    lastname = models.CharField(max_length=100)

    def full_name(self):
        return f"{self.firstname} {self.lastname}"

    def __str__(self):
        return self.full_name()


class Post(models.Model):
    title = models.CharField(max_length=150)
    excerpt = models.CharField(max_length=200)
    image_name = models.CharField(max_length=100)
    date = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(unique=True, db_index=True)
    content = models.TextField(validators=[MinLengthValidator(10)])
    author = models.ForeignKey(
        Author, on_delete=models.SET_NULL, null=True, related_name="posts"
    )

    def __str__(self):
        return self.title


class Contact(models.Model):
    name = models.CharField(max_length=200)
    email = models.EmailField()
    subject = models.TextField()

    def __str__(self):
        return self.name


class Blog(models.Model):
    title1 = models.CharField(max_length=150)
    excerpt1 = models.CharField(max_length=200)
    image_name1 = models.CharField(max_length=100)
    date1 = models.DateTimeField(auto_now_add=True)
    slug1 = models.SlugField(unique=True, db_index=True)
    content1 = models.TextField(validators=[MinLengthValidator(10)])
    author1 = models.ForeignKey(
        Author, on_delete=models.SET_NULL, null=True, related_name="blogs"
    )

    def __str__(self):
        return self.title1



class Idea(models.Model):
    title2 = models.CharField(max_length=150)
    excerpt2 = models.CharField(max_length=200)
    image_name2 = models.CharField(max_length=100)
    date2 = models.DateTimeField(auto_now_add=True)
    slug2 = models.SlugField(unique=True, db_index=True)
    content2 = models.TextField(validators=[MinLengthValidator(10)])
    author2 = models.ForeignKey(
        Author, on_delete=models.SET_NULL, null=True, related_name="ideas"
    )

    def __str__(self):
        return self.title2

dapecon/dapecon/dapapp/forms.py
from django import forms
from .models import Post

class BlogForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'content', 'author']


class ContactForm(forms.Form):
    name = forms.CharField(max_length=200)
    email = forms.EmailField()
    phone = forms.CharField(max_length=15)  # Adjust the max_length according to your needs
    message = forms.CharField(widget=forms.Textarea)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['phone'].widget.attrs.update({'type': 'tel', 'placeholder': 'Πληκτρολόγησε τον αριθμό τηλεφώνου σου'})

dapecon/dapecon/dapapp/views.py
from django.shortcuts import render, redirect
from .models import Post, Blog, Idea
from django.core.mail import send_mail
from .forms import ContactForm
from django.shortcuts import render, get_object_or_404
from django.shortcuts import render, redirect
from .models import ContactMessage


def thank_you(request):
    return render(request, 'thankyou.html')

def contact_view(request):
    message_sent = False

    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            ContactMessage.objects.create(
                name=form.cleaned_data['name'],
                email=form.cleaned_data['email'],
                phone=form.cleaned_data['phone'],
                message=form.cleaned_data['message']
            )
            message_sent = True
            return render(request, 'thankyou.html')
    else:
        form = ContactForm()

    return render(request, 'contact_form.html', {'form': form, 'message_sent': message_sent})


def post_detail(request, slug):
    post = get_object_or_404(Post, slug=slug)
    context = {'post': post}
    return render(request, 'post_detail.html', context)



def post_detail1(request, slug1):
    blog = get_object_or_404(Blog, slug1=slug1)
    context = {'post': blog}  # Change 'blog' to 'post' to match the template variable name
    return render(request, 'post_detail1.html', context)



def blogs(request):
    blogs = Blog.objects.all().order_by('-date1')
    sorted_posts = Post.objects.all().order_by('-date')
    context1 = {
        'blogs': blogs, 
         'posts': sorted_posts,
    }
    return render(request, 'anakinosis.html', context1)





def arxiki(request):
    latest_anakinosis_post = Blog.objects.latest('date1')
    latest_posts_post = Post.objects.latest('date')
    latest_ideas_post = Idea.objects.latest('date2')
    context = {
        'latest_anakinosis_post': latest_anakinosis_post,
        'latest_posts_post': latest_posts_post,
        'latest_ideas_post': latest_ideas_post,
    }
    return render(request, 'arxiki.html', context)

    

def istoria(request):
    ideas = Idea.objects.all().order_by('-date2')
    context3 = {
        'ideas': ideas,
    }
    return render(request, 'istoria.html', context3)






   

    
def post_detail2(request, slug2):
    idea = get_object_or_404(Idea, slug2=slug2)
    context = {'idea': idea}  # Change 'blog' to 'post' to match the template variable name
    return render(request, 'post_detail2.html', context)

dapecon/dapecon/dapapp/templates/anakinosis.html
{% extends 'arxiki.html' %}
{% block css_files %}
{% load static %}
<link rel="stylesheet" href="{% static 'blogs.css' %}">
{% endblock %}
{% block title %}Ανακοινώσεις - ΔΑΠ ΟΙΚΟΝΟΜΙΚΟΥ ΑΠΘ{% endblock %}
{% block content %}
<body>
    <h1 style="margin-top: 100px; color: darkblue; font-family: Arial, Helvetica, sans-serif; 
    font-size: 25px; text-align: center;">
        Ανακοινώσεις.
    </h1>
    <section style="display: flex; flex-wrap: wrap;">
        {% for blog in blogs %}
        <a href="{% url 'dap:post_detail1' slug1=blog.slug1 %}" class="postt">
            <div style="border: solid darkblue; border-radius: 10px; margin: 10px; padding: 10px; flex-basis: calc(33.33% - 20px);">
                <h2 style="font-family: Arial, Helvetica, sans-serif; color: darkblue; margin-top: 0;">{{ blog.title1 }}</h2>
                <img src="{% static '/'|add:blog.image_name1 %}" style="width: 100%; max-width: 450px; height: auto; margin-bottom: 10px;">
                <p style="font-family: Arial, Helvetica, sans-serif;">{{ blog.content1|truncatechars:40 }}</p>
                <p style="font-family: Arial, Helvetica, sans-serif; color: black;">Date Created: {{ blog.date1 }}</p>
            </div>
        </a>
        {% empty %}
        <p>No blogs found.</p>
        {% endfor %}
    </section>
</body>

</html>





<!DOCTYPE html>
<html>
<body>
    
    <h1 style="margin-top: 100px; color: darkblue; font-family: Arial, Helvetica, sans-serif; 
    font-size: 25px; text-align: center;">
    Οι δράσεις μας.
</h1>
    

    <section style="display: flex; flex-wrap: wrap;">
        {% for post in posts %}
        <a href="{% url 'dap:post_detail' slug=post.slug %}" class="postt">
            <div style="border: solid darkblue; border-radius: 10px; margin: 10px; padding: 10px; flex-basis: calc(33.33% - 20px);">
                <h2 style="font-family: Arial, Helvetica, sans-serif; color: darkblue; margin-top: 0;">{{ post.title }}</h2>
                <img src="{% static '/'|add:post.image_name %}" style="width: 100%; max-width: 450px; height: auto; margin-bottom: 10px;">
                <p style="font-family: Arial, Helvetica, sans-serif;">{{ post.content|truncatechars:40 }}</p>
            
                <p style="font-family: Arial, Helvetica, sans-serif; color: black;">Date Created: {{ post.date }}</p>
            </div>
        </a>
        {% empty %}
        <p>No blogs found.</p>
        {% endfor %}
       
    </section>
</body>

{% endblock %}
</html>


dapecon/dapecon/dapapp/templates/arxiki.html
{% load static %}
{% block css_files %}
<link rel="stylesheet" href="{% static 'arxiki.css' %}">
{% endblock %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{% block title %}Αρχική - ΔΑΠ ΟΙΚΟΝΟΜΙΚΟΥ ΑΠΘ{% endblock %}</title>

</head>
<body > 
    <link rel="icon" type="image/png" href="{% static 'icon1.png' %}">

 <a href="http://127.0.0.1:8000/"><img src="{% static 'icon1.png' %}" alt="DAP SYMBOL" class="foto1"> </a>
 <div class="menu-items" style="margin-top: -50px;">







    <ul class="navbar" style="font-size: 10px; margin-left: 200px; margin-right: -60px; ">
        <li class="nav-item-left" style=" margin-right: -50px"><a href="http://127.0.0.1:8000/" class="a1">Αρχική</a></li>
        <li class="nav-item" style="margin-right: -60px;"><a href="/anakinoseis/" class="a1">Ανακοινώσεις</a></li>
        <li class="nav-item" style="margin-right: -60px;"><a href="/istoria/" class="a1">Η Ιστορία μας</a></li>
        <li class="nav-item"><a href="/contact/" class="a1">Επικοινωνία</a></li>
    </ul>
    
  


</div>
<style>
 
  /* Existing CSS styles */

  /* Hamburger menu styles */
  .hamburger {
    display: none;
    cursor: pointer;
    position: fixed;
    top: 20px;
    right: 20px;
    z-index: 9999;
  }

  .bar {
    display: block;
    width: 25px;
    height: 3px;
    margin: 5px auto;
    transition: all 0.3s ease-in-out;
    background-color: darkblue;
  }

  @media (max-width: 600px) {
    .navbar{
      display: none;
    }

    /* Show hamburger menu on smaller screens */
    .hamburger {
      display: block;
    }

    /* Animate hamburger icon */
    .hamburger.active .bar:nth-child(2) {
      opacity: 0;
    
    }

    .hamburger.active .bar:nth-child(1) {
      transform: translate(8px) rotate(45deg);
    }

    .hamburger.active .bar:nth-child(3) {
      transform: translate(-8px) rotate(-45deg);
    }

    /* Update navbar styles for mobile */
    .navbar {
      position: fixed;
      top: 0;
      right: 0;
      width: 100%;
      background-color: black;
      flex-direction: column;
      align-items: flex-start;
      justify-content: center;
      padding: 40px;
      text-align: center;
      z-index: 999;
      height: 110vh; /* Set the height to full viewport height */
      }

    .navbar.active {
      display: flex;
    }

    .nav-item {
      margin: 10px 0;
    }

    /* Adjust the position of the last menu item */
   

  }
</style>


<div class="hamburger">
  <span class="bar"></span>
  <span class="bar"></span>
  <span class="bar"></span>
</div>

<script>
  document.addEventListener('DOMContentLoaded', () => {
    const hamburger = document.querySelector('.hamburger');
    const navbar = document.querySelector('.navbar');

    hamburger.addEventListener('click', () => {
      hamburger.classList.toggle('active');
      navbar.classList.toggle('active');
    });

    document.querySelectorAll('.a1').forEach((n) => {
      n.addEventListener('click', () => {
        hamburger.classList.remove('active');
        navbar.classList.remove('active');
      });
    });
  });
</script>


</body>

{% block content %}

<h3 style="text-align: center; font-family: Arial, Helvetica, sans-serif;
color: darkblue; font-size: 25px;">Αρχική</h3>
<img src="{% static 'body.png' %}" alt="Your Image" style="margin-top: 250px; position: absolute;top: 50%; 
left: 50%; transform: translate(-50%, -50%); border: 7px solid darkblue; border-radius: 5px;
height: 100vh; ">

<style>
.postt {
  color: darkblue;
  text-decoration: none;
}

.postt:hover {
  /* Remove hover effect specifically for posts */
  text-decoration: none;
}

.postt.clicked {
  text-decoration: none;
  color: darkblue;
}
</style>





<h3 style="margin-top: 800px; text-align: center; font-family: Arial, Helvetica, sans-serif; font-size: 25px; 
 color: darkblue;">
Η τελευταία ανακοίνωση μας:
</h3>



{% if latest_anakinosis_post %}
<div style="margin: 10px; text-align: center; margin-top: ;">
  <a href="{% url 'dap:post_detail1' slug1=latest_anakinosis_post.slug1 %}" class="postt">
    <div style="display: inline-block; border: solid darkblue; border-radius: 10px; padding: 10px;">
      <h2 style="font-family: Arial, Helvetica, sans-serif; color: darkblue; margin-top: 0; font-size: 16px;">{{ latest_anakinosis_post.title1 }}</h2>
      <div style="max-width: 400px; margin: 0 auto;">
        <img src="{% static '/'|add:latest_anakinosis_post.image_name1 %}" style="max-width: 100%; height: auto; margin-bottom: 10px;">
      </div>
      <p style="font-family: Arial, Helvetica, sans-serif; font-size: 14px;">{{ latest_anakinosis_post.content1|truncatechars:40 }}</p>
      <p style="font-family: Arial, Helvetica, sans-serif; color: black; font-size: 12px;">Date Created: {{ latest_anakinosis_post.date1 }}</p>
    </div>
  </a>
</div>



{% else %}
<p>No latest post found for anakinosis.</p>
{% endif %}


<h3 style="color: darkblue; font-size: 25px; 
    text-align: center; font-family: Arial, Helvetica, sans-serif;">Οι δράσεις μας:</h3>

{% if latest_posts_post %}
<div style="margin: 10px; text-align: center; ">
  <a href="{% url 'dap:post_detail' slug=latest_posts_post.slug %}" class="postt">
    <div style="display: inline-block; border: solid darkblue; border-radius: 10px; padding: 10px;">
      <h2 style="font-family: Arial, Helvetica, sans-serif; color: darkblue; margin-top: 0; font-size: 16px;">{{ latest_posts_post.title }}</h2>
      <div style="max-width: 400px; margin: 0 auto;">
        <img src="{% static '/'|add:latest_posts_post.image_name %}" style="max-width: 100%; height: auto; margin-bottom: 10px;">
      </div>
      <p style="font-family: Arial, Helvetica, sans-serif; font-size: 14px;">{{ latest_posts_post.content|truncatechars:40 }}</p>
      <p style="font-family: Arial, Helvetica, sans-serif; color: black; font-size: 12px;">Date Created: {{ latest_posts_post.date }}</p>
    </div>
  </a>
</div>
{% else %}
<p>No latest post found for posts.</p>
{% endif %}



<h3 style="font-family: Arial, Helvetica, sans-serif; color: darkblue; text-align: center;
font-size: 25px;">Οι ιδέες μας:</h3>


{% if latest_ideas_post %}
<div style="margin: 10px; text-align: center; ">
  <a href="{% url 'dap:post_detail2' slug2=latest_ideas_post.slug2 %}" class="postt">
    <div style="display: inline-block; border: solid darkblue; border-radius: 10px; padding: 10px;">
      <h2 style="font-family: Arial, Helvetica, sans-serif; color: darkblue; margin-top: 0; font-size: 16px;">{{ latest_ideas_post.title2 }}</h2>
      <div style="max-width: 400px; margin: 0 auto;">
        <img src="{% static '/'|add:latest_ideas_post.image_name2 %}" style="max-width: 100%; height: auto; margin-bottom: 10px;">
      </div>
      <p style="font-family: Arial, Helvetica, sans-serif; font-size: 14px;">{{ latest_posts_post.content2|truncatechars:40 }}</p>
      <p style="font-family: Arial, Helvetica, sans-serif; color: black; font-size: 12px;">Date Created: {{ latest_ideas_post.date2 }}</p>
    </div>
  </a>
</div>
{% else %}
<p>No latest post found for anakinosis.</p>
{% endif %}


{% endblock %}
</html>

dapecon/dapecon/dapapp/templates/contact_form.html
{% extends 'arxiki.html' %}
{% load static %}

{% block title %}Επικοινωνία - ΔΑΠ ΟΙΚΟΝΟΜΙΚΟΥ ΑΠΘ{% endblock %}

{% block css_files %}
<link rel="stylesheet" href="{% static 'ideas.css' %}">

<style>
    /* Existing styles... */

    /* New style for phone number input field */
    .phone-label,
    .phone-input {
        display: flex;
        flex-direction: column;
    }

    .phone-label label {
        font-size: 16px;
        color: #333;
        margin-bottom: 5px;
    }

    .phone-input input[type="tel"],
    .phone-input input[type="tel"]:focus {
        border: 1px solid #ccc;
        padding: 10px;
        width: 100%;
        margin-bottom: 10px;
        border-radius: 5px;
        box-sizing: border-box;
    }
   

    .center {
        display: flex;
        justify-content: center;
        align-items: center;
        height: 100vh;
        flex-direction: column;
    }
    .border{
        border: 4px solid darkblue;
        background-color: darkblue;
        display: inline;    
    }

    h3 {
        
        text-align: center;
        align-items: center;
        border-radius: 7px;
        font-family: Arial, Helvetica, sans-serif;
        color: white;
        font-size: 30px;
    }

    form {
        width: 100%;
        max-width: 400px;
        padding: 20px;
        background-color: #f7f7f7;
        border-radius: 5px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    }

    label {
        font-size: 16px;
        color: #333;
        margin-bottom: 5px;
    }

    input,
    textarea {
        border: 1px solid #ccc;
        padding: 10px;
        width: 100%;
        margin-bottom: 10px;
        border-radius: 5px;
        box-sizing: border-box;
    }

    button {
        border: none;
        margin-top: 20px;
        padding: 10px 20px;
        font-size: 16px;
        color: #fff;
        background-color: darkblue;
        border-radius: 4px;
        cursor: pointer;
        width: 100%;
        transition: background-color 0.3s;
    }

    button:hover {
        background-color: #0056b3;
    }

    @media only screen and (min-width: 480px) {
        form {
            width: 400px;
        }
    }
    input[type="tel"] {
        border: 1px solid #ccc;
        padding: 10px;
        width: 100%;
        margin-bottom: 10px;
        border-radius: 5px;
        box-sizing: border-box;
    }
</style>
{% endblock %}

{% block content %}
<body style="font-family: Arial, Helvetica, sans-serif;">
    <div style="text-align: center; margin-top: 100px;">

    <h3 class="border">Συνδέσου άμεσα μαζί μας.</h3>
</div>
<p style="margin-top: -120px;">
    <div class="center">
        <form method="post">
            {% csrf_token %}
            
            <div>
                <label for="id_name">Ονοματεπώνυμο:</label>
                <input type="text" name="name" id="id_name" placeholder="Πληκτρολόγησε το ονοματεπώνυμο σου" required>
            </div>
            
            <div>
                <label for="id_email">Email:</label>
                <input type="email" name="email" id="id_email" placeholder="Πληκτρολόγησε το email σου" required>
            </div>
            
            <!-- New phone number input field -->
           
                <label for="id_phone">Τηλέφωνο:</label>
                <div>
                <input type="tel" name="phone" id="id_phone" placeholder="Πληκτρολόγησε τον αριθμό τηλεφώνου σου" required>
            </div>
            
            <div>
                <label for="id_message">Μήνυμα:</label>
                <textarea name="message" id="id_message" placeholder="Γράψε μας τι χρειάζεσαι... π.χ. σημειώσεις στο Μάρκετινγκ" required></textarea>
            </div>
            
            <button type="submit">Υποβολή</button>
        </form>
    </div>
</p>
</body>
{% endblock %}

dapecon/dapecon/dapapp/templates/istoria.html
{% extends 'arxiki.html' %}
{% load static %}
<html>
{% block title %}Ιστορία - ΔΑΠ ΟΙΚΟΝΟΜΙΚΟΥ ΑΠΘ {% endblock %}

{% block content %}


<style>

.foto1{
  width: 190px;
  height: 170px;
}




  
  .navbar li {
    display: inline-block; /* Display list items horizontally */
    margin-right: 10px; /* Add spacing between list items */
    text-decoration: none;
    padding-left: 50px;
    padding-right: 50px;
  
  }
  
.navbar li .a1{
  color: darkblue;
  text-decoration: none;
  font-family: Arial, Helvetica, sans-serif;
  font-size: 25px;
  
}
.a1{
  position: relative;
  letter-spacing: 0.5px;
  padding: 0;

}
.a1:after{
  content: "";
  position: absolute;
  background-color: darkblue;
  height: 3px;
  width: 0;
  left: 0;
  bottom: -10px;
}
.a1:hover:after{
  width: 100%;

}


.postt {
  color: darkblue;
  text-decoration: none;
}

.postt:hover {
  /* Remove hover effect specifically for posts */
  text-decoration: none;
}

.postt.clicked {
  text-decoration: none;
  color: darkblue;
}



</style>











<body>
  <style>
    h3 {
      font-family: Arial, Helvetica, sans-serif;
      margin-top: 100px;
      text-align: center;
      font-size: 25px;
      color: darkblue;
    }
    
    
    
    .content-container {
      text-align: center;
      border: 5px solid darkblue;
      background-color: darkblue;
      border-radius: 20px;
      color: white;
      font-family: Arial, Helvetica, sans-serif;
      margin: 20px auto;
      padding: 20px;
      max-width: 800px;
    }
    
    @media (max-width: 600px) {
      .image {
        height: 70vh;

      }
      
      .content-container {
        margin: 20px;
      }
    }
  </style>

  <h3>Η ιστορία μας.</h3>
<div  style="text-align: center; ">
  <img src="{% static 'back1.jpg' %}" alt="Background Image" class="image" style="
        height: 70vh; border: 7px solid darkblue; border-radius: 6px; ">
</div>
  <div class="content-container">
    <p>Η  ΔΑΠ-ΝΔΦΚ του Αριστοτελείου Πανεπιστημίου Θεσσαλονίκης και τμήματος Οικονομικών επιστημών<br>
      μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλαμπλα<br>
      μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα<br>
      μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα<br>
      μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα<br>
      μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα<br>
      μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα<br>
      μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα<br>
      μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα<br>
      μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα<br>
      μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα<br>
      μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα<br>
      μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα<br>
      μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα μπλα.</p>
  </div>

</body>
</html>



<html>
    <body>
        <h3 style="text-align: center; font-size: 25px; 
        font-family: Arial, Helvetica, sans-serif; color: darkblue;
        margin-top: 100px;">Οι ιδέες μας.</h3>
        <section style="display: flex; flex-wrap: wrap; ">
            {% for idea in ideas %}
            <a  href="{% url 'dap:post_detail2' slug2=idea.slug2 %}" class="postt">
                <div style="border: solid darkblue; border-radius: 10px; margin: 10px; padding: 10px; flex-basis: calc(33.33% - 20px);
                margin-top: 100px; margin-left: 20px">
                    <h2 style="font-family: Arial, Helvetica, sans-serif; color: darkblue; margin-top: 0;">{{ idea.title2 }}</h2>
                    <img src="{% static '/'|add:idea.image_name2 %}" style="width: 100%; max-width: 450px; height: auto; margin-bottom: 10px;">
                    <p style="font-family: Arial, Helvetica, sans-serif;">{{ idea.content2|truncatechars:30 }}</p>
                    <p style="font-family: Arial, Helvetica, sans-serif; color: black;">Date Created: {{ idea.date2 }}</p>
                </div>
            </a>
            {% empty %}
            <p>No blogs found.</p>
            {% endfor %}
        </section>
    </body>
    {% endblock %}
</html>

dapecon/dapecon/dapapp/templates/thankyou.html
{% extends 'arxiki.html' %}
{% load static %}

{% block content %}
<html>
<body>
    <style>
        h1 {
            text-align: center;
            font-size: 25px;
            font-family: Arial, Helvetica, sans-serif;
            color: darkblue;
            margin-top: 100px;
        }

        p {
            text-align: center;
            color: darkblue;
            font-family: Arial, Helvetica, sans-serif;
        }

        @media only screen and (max-width: px) {
            h1 {
                font-size: 20px;
                margin-top: 50px;
            }

            p {
                font-size: 16px;
                margin-bottom: 50px;
            }
        }
    </style>

    <h1>Thank You!</h1>
    <p>Σε ευχαριστούμε για το μήνυμα. Θα σου απαντήσουμε σύντομα.</p>
</body>

{% endblock %}
</html>